### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by fuzetsu** [fuzetsu/zaftig#6]
The name zaftig was chosen initially because it was fairly unique, and justified the use of `z` but it's not particularly meaningful to what it does, and a bit hard to type (based on some reports).

Currently considering:
- zafty

**Comment by osban** [comment]
"...a bit hard to _pronounce_" mostly 😉

**Comment by fuzetsu** [comment]
closing this for now, the name has grown on me and has been around for a while now 😄
